### ISSUE TITLE
centering on current scene

### ISSUE THREAD

**Issue by martinex** [3D-e-Chem/molviewer-tsx#21]
A button in the web browser would be useful that centers the current scene on the screen.

**Comment by sverhoeven** [comment]
The molviewer uses the setVisibility() to hide/show components.
NGL autoview() calculates the bounding box based on all components, regardless if they are shown or hidden. So using autoview() does not give the expected results.

I see 2 solutions
1. Calculate the bounding box of only visible components, but NGL is missing an obvious API to do this
2. When component is hidden remove it from the stage, so it is not included in the default bounding box calculation, but this is a major refactor
